#!/bin/sh

# grab the current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# install node_modules using bazel's node version
bazel run @yarn//:yarn install

# run the parcel dev server passing it the full path
bazel run :parcel $DIR/public/index.html
